### ISSUE TITLE
Questions about Vmamba with pre-trained weight

### ISSUE THREAD

**Issue by fuyimin96** [ChiShengChen/ResVMamba#3]
As shown in Table 4 of your paper, finetuning Vmamba with retrained weight gets the best performance.
I want to do some modifications based on normal fine-grained datasets but get unsatisfactory results.
Can you please provide me the detail implementation of how you fine-tune mamba-s with pre-trained weights?
Such as lr, epochs, and other hyperparameter settings.
Thanks!

**Comment by ChiShengChen** [comment]
Hi @fuyimin96,

I use the same setting as VMamba.
